### ISSUE TITLE
Use of isomorphic-fetch dependency

### ISSUE THREAD

**Issue by MarkHerhold** [paulvanbladel/aurelia-auth#129]
Why does this library ship with a polyfilled fetch dependency? In my opinion this library should use the browser's default fetch client and end users can provide a polyfill as needed.

**Comment by paulvanbladel** [comment]
@mbroadst what is your view on this? Thanks.

**Comment by mbroadst** [comment]
this should be fine, the isomorphic-fetch was added because we were trying to use webpack and the existing module at the time imported `fetch`. It should be enough to simply remind the users of the library that they must import their own fetch polyfill in the event that the browser doesn't support it
