### ISSUE TITLE
Can't post to Oauth2 Service with authService.login()

### ISSUE THREAD

**Issue by Skylertodd** [paulvanbladel/aurelia-auth#23]
Currently the way AuthService.Login is implemented it will not post to any .net Oauth2 Service because it strictly requires the post data to be formatted with 'application/x-www-form-urlencoded'.

The current implementation seems really close... but I am unable to get it to work without monkey patching in an alternate to your auth function.

Currently I am patching this in so that I can use the content = arguments[0]; for my url escaped string.

```javascript
	monkeyPatchAuthService(){
		this.auth.login = function login(email, password) {
						var _this2 = this;

						var loginUrl = this.auth.getLoginUrl();
						var content;
						
						if (typeof arguments[1] !== 'string') {
							content = arguments[0];
						} else {
							content = { 'email': email, 'password': password };
						}

						return this.http.createRequest(loginUrl).asPost().withContent(content).send().then(function (response) {
							_this2.auth.setToken(response);
							return response;
						});
					}
	}
```

After patching that in I can now call the following and it seems to work.
```javascript
var loginObj = $.param({'username': this.username, 'password': this.password, grant_type: "password"});
		
		return this.auth.login(loginObj)
		.then(response=>{
```

Please let me know if you need any other info.

**Comment by paulvanbladel** [comment]
Strange but interesting.
1. do you have somewhere your backend on github or another reference implementation similar to yours?
2. can you please take a screen shot from network f12 tools showing how things go over the wire in the two situations (my code and yours)?
thanks.

**Comment by mrmofo** [comment]
@paulvanbladel  You can use the code here to create a back end: 
[AspNetIdentity.WebApi GitHub](https://github.com/tjoudeh/AspNetIdentity.WebApi)

I'd love to pop up a site real fast that you could use but it is on my computer at work.

**We tried to use it several different ways to get it to work.**

1. Passing in the 'email' and 'password' to the Login function - this sets the format in the header to 'application/json' - which doesn't work and we get a 'Bad Reqest'

2. Passing in a new FormData obj with the properties of username, password, and grant_type (since the code checked the first arg to see if it was an argument. - this didn't work because the format of the body just wasn't right at all. (kind of a stab in the dark)

3. Lastly - creating the object this way:  
```javascript
var loginObj = $.param({'username': this.username, 'password': this.password, grant_type: "password"}); 
```
Passing it into the login function - login(loginObj) - but
```javascript
if (typeof arguments[0] === 'object'){}
```
Will return false.

**3 1/2:** Actually create a new String:
```
var loginObj = new String($.param({'username': this.username, 'password': this.password, grant_type: "password"})); 
```
This will actually return true when the checking the first arg to see if it is an object. But, when the http call is made it it puts sets the format to 'application/json' because what is passed is a string and has quote marks around it. 


**I like the monkey path above** where instead of checking to see if the first argument is an object - checking the second object to see if it is a string (or undefined - however). This should be a minor tweak and when you pass the loginObj constructed like this:
```javascript
var loginObj = $.param({'username': this.username, 'password': this.password, grant_type: "password"}); 
```
it will automagically assign the format to 'application/x-www-form-urlencoded' and work like a charm. 

> As a side note the spec for OAuth 2.0 says, from what I can read, that it has to be 'application/x-www-form-urlencoded'  - here: https://tools.ietf.org/html/rfc6749#section-4.3.2

Thanks!

**Comment by paulvanbladel** [comment]
Euh... the login method has nothing to do with oauth. It is simple username password auth.
The authenticate method goes to the oauth endpoint.

**Comment by paulvanbladel** [comment]
Maybe this helps:
https://weblog.west-wind.com/posts/2012/Aug/16/Mapping-UrlEncoded-POST-Values-in-ASPNET-Web-API

**Comment by mrmofo** [comment]
Hey Paul - 

I had looked through the authenticate method

```javascript
	authenticate(name, redirect, userData) {
		var provider = this.oAuth2;
		if (this.config.providers[name].type === '1.0'){
			provider = this.oAuth1;
		};

		return provider.open(this.config.providers[name], userData || {})
		.then((response) => {
			this.auth.setToken(response, redirect);
			return response;
		});
	};
```

which calls `provider.open`: 

```javascript
    open(options, userData) {
        authUtils.extend(this.defaults, options);
        var stateName = this.defaults.name + '_state';

        if (authUtils.isFunction(this.defaults.state)) {
            this.storage.set(stateName, this.defaults.state());
        } else if (authUtils.isString(this.defaults.state)) {
            this.storage.set(stateName, this.defaults.state);
        }

        var url = this.defaults.authorizationEndpoint + '?' + this.buildQueryString();

        var openPopup;
            if (this.config.platform === 'mobile') {
              openPopup = this.popup.open(url, this.defaults.name, this.defaults.popupOptions, this.defaults.redirectUri).eventListener(this.defaults.redirectUri);
            } else {
              openPopup = this.popup.open(url, this.defaults.name, this.defaults.popupOptions, this.defaults.redirectUri).pollPopup();
            }

        var self = this;
        return openPopup
            .then((oauthData) => {
                if (self.defaults.responseType === 'token') {
                    return oauthData;
                }
                if (oauthData.state && oauthData.state !== self.storage.get(stateName)) {
                    return Promise.reject('OAuth 2.0 state parameter mismatch.');
                }
                return self.exchangeForToken(oauthData, userData);
            });
    };
```
Which looks great for a Facebook/Google/etc type auth where they control the login page and you provide that pop-up page, pass in the information it needs, and it calls back. -- and to be fair I could probably just create a 'universal' login page that is hosted by my oauth server and have it respect that paradigm. 

>The difference to me is when you login to facebook - on facebook.com - you don't get a pop-up or anything else - it's their domain - it's just an email and password field that you fill out and sign in. Now if you use facebook oauth to login into a different site (eg github.com) - you would get the popup and go through the handshake. 

I was just wanting to call `https://the_auth_url.com/oauth/token`, pass in the username and password and get just back my bearer token - just feels like the easiest thing to me. 

I guess another option is doing more of what the link you provided is saying - on the `AcccountController` create a `Login` method, decorate it with anonymous and have it return what `../oauth/token` would return. 

Maybe this helps define the use case a bit more. 

I appreciate your work and your time.

Best,
Mike

**Comment by paulvanbladel** [comment]
I think you gave the solution, jump to your server side account controller and provide the apropriate method.

**Comment by Skylertodd** [comment]
This is with my MonkeyPatch included in the original message
```code
POST http://localhost:10226/oauth/token HTTP/1.1
Host: localhost:10226
Connection: keep-alive
Content-Length: 59
Origin: http://localhost:8080
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36
Content-Type: text/plain;charset=UTF-8
Accept: */*
Referer: http://localhost:8080/
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.8

username=MyUserName&password=MyPassword&grant_type=password
```
This is using formdata
```code
POST http://localhost:10226/oauth/token HTTP/1.1
Host: localhost:10226
Connection: keep-alive
Content-Length: 359
Origin: http://localhost:8080
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary59w9vVfu9Gk2uPvT
Accept: */*
Referer: http://localhost:8080/
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.8

------WebKitFormBoundary59w9vVfu9Gk2uPvT
Content-Disposition: form-data; name="username"

MyUserName
------WebKitFormBoundary59w9vVfu9Gk2uPvT
Content-Disposition: form-data; name="password"

MyPassword
------WebKitFormBoundary59w9vVfu9Gk2uPvT
Content-Disposition: form-data; name="grant_type"

password
------WebKitFormBoundary59w9vVfu9Gk2uPvT--

```

This is with your original code.
```code
POST http://localhost:10226/oauth/token HTTP/1.1
Host: localhost:10226
Connection: keep-alive
Content-Length: 46
Origin: http://localhost:8080
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36
Content-Type: application/json
Accept: */*
Referer: http://localhost:8080/
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.8

{"email":"MyUserName","password":"MyPassword"}
```

**Comment by paulvanbladel** [comment]
please update the .net backend as per https://weblog.west-wind.com/posts/2012/Aug/16/Mapping-UrlEncoded-POST-Values-in-ASPNET-Web-API, 
in such a way it can receive a simple post request.

**Comment by mrmofo** [comment]
Thanks Paul for looking into this - I really appreciate your time. However, to note - the link doesn't address the problem.

1. The write up is pretty old and discusses .Net Web API *1*
2. The backend code is Web API 2 hosted by OWIN 
3. All the services for the backend already receive application/json requests 

There is only one call that does not post the values in the body of the request using JSON and that is the "TokenEndpointPath" (/token) and there is no way to configure it to do so. it accepts only "x-www-form-urlencoded" type bodies 

The configuration for this (for OWIN) looks like this:

```c#
OAuthAuthorizationServerOptions OAuthServerOptions = new OAuthAuthorizationServerOptions()
{
    //For Dev enviroment only (on production should be AllowInsecureHttp = false)
    AllowInsecureHttp = _allowInsecureHttp,
    TokenEndpointPath = new PathString("/oauth/token"),
    AccessTokenExpireTimeSpan = TimeSpan.FromDays(1),
    Provider = new CustomOAuthProvider(),
    AccessTokenFormat = new CustomJwtFormat(_baseUrl) 
};
```

To maybe clear up a bit of confusion - the workflow type we are using is like this:
http://oauthlib.readthedocs.org/en/latest/oauth2/grants/password.html

The reason is because we own every app that will be using this oAuth provider and complete trust them. 

if we were to, for some reason, allow other clients use our oAuth, we would definitely have to create a scheme more like this (which is how your code does it):

http://oauthlib.readthedocs.org/en/latest/oauth2/grants/authcode.html
or 
http://oauthlib.readthedocs.org/en/latest/oauth2/grants/implicit.html

This obviously isn't a bug in your code - your code works great and as intended - I just want to make sure the potential area of improvement was being understood. 

Best,
Mike

**Comment by paulvanbladel** [comment]
Hi Mike,
These docs shed quite another light on the problem. I understand now the architecture and also the confusion. For me, the login method is just something completely apart from Oauth, whereas you want to use it in a oauth context with a specific 'grant_type'.
I'm a pragmatic guy, so very willing to update the code, but I want to be sure it doesn't break any existing things (which, at first glance, is not the case).
So, I'll update the code, but in case a backward compat issue arises, we have to look for another creative solution :)

**Comment by paulvanbladel** [comment]
Mike, 

Please try aurelia-auth 0.9.16.
cheers

**Comment by mrmofo** [comment]
Thanks Paul. Just an FYI. I did branch and took a shot at making the authenticate method more aware. I don't know if you want to take a look at it or not but I tried to change as little as possible with adding this option of oAuth2. 

Best!
Mike

**Comment by paulvanbladel** [comment]
Sure, i saw the update in readme.
Is it possible you did copy paste error? The alternative code sample is given twice i think.
Cheers

**Comment by mrmofo** [comment]
Yup - looks like I screwed that up pretty bad. First time playing really playing with github - sorry about that!

Let me know what you think. 

Best!
Mike

**Comment by paulvanbladel** [comment]
Haha, no worries.
Will look into it tomorrow, getting late here in Europe.

**Comment by paulvanbladel** [comment]
Mike,
 Is 0.9.16 solving your issue? 
Thx

**Comment by Skylertodd** [comment]
Paul, 0.9.16 seems to be working out.  Thank you for your support!

**Comment by mrmofo** [comment]
Hey Paul - just echoing Skyler here - We are up and working with your code. Thanks a lot!
