### ISSUE TITLE
include token header only for specific domains

### ISSUE THREAD

**Issue by DiknT** [paulvanbladel/aurelia-auth#82]
currently the jwt token is send with every fetch request, even if not required, e.g. within the oauth requests to social providers or any other domain you use fetch for. Proof me wrong but I guess this is bad practice.
What do you think about having kind of a whitelist in the config file, an array of domain-strings for which the token should be set only. In the interceptor then the request url could be matched with this whitelisted domains and the token only set if appropriate. Any thoughts on this?

**Comment by RWOverdijk** [comment]
@DiknT That sounds about right. Although a whitelist might be a bit hacky.

**Comment by Vidarls** [comment]
Would it not be possible to do an API connection class that encapsulates a separate fetch client instance that is configured with access token?

**Comment by RWOverdijk** [comment]
@Vidarls That's what I'm doing over at [my fork](https://github.com/SpoonX/aurelia-orm). The next release will have this feature implemented. To give you an idea, it'll use aurelia api. https://github.com/SpoonX/aurelia-api/blob/master/doc/getting-started.md#multiple-endpoints

**Comment by RWOverdijk** [comment]
fyi, this is the PR for the next release: https://github.com/SpoonX/aurelia-auth/pull/22

**Comment by Vidarls** [comment]
That looks promising, also appreciate that you added typescript defs for the project. 

But what is the relationship between this project and your fork @RWOverdijk ? Are you and @paulvanbladel collaborating, are you taking the project in different directions? Kind of hard to know if one is considered the official or if they should be considered to separate projects with separate goals?

Asking both from a consumer as well as contributor standpoint

**Comment by RWOverdijk** [comment]
@Vidarls I understand, I have a weird agreement with Paul about this. I'll explain:

I helped Paul maintain this module for a little bit because had a lot of stuff on his plate. At some point, I figured that the amount of work, and direction I was taking the module (play nice with multiple endpoints, my api plugin etc), were reason enough to make a fork. So I did. Now we (SpoonX) actively develop on that fork, and I help Paul maintain this one. So any PR or issue on this repo is one I'll look at. In reality, both repositories are slowly growing apart and it's really up to you to decide which you want to use.

So even though I don't actively develop for this one, rest assured it's still maintained and PRs are welcome. :)
